language: node_js
node_js:
  - 'stable'
install: npm install
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=testing
    - DATABASE_DEV=postgres://cpysnlqqbpwqjf:bcbfbc86cb607c51098522a6da8dbfa8c2b6d5afa6d93b90e3ed839237eab54a@ec2-54-227-245-146.compute-1.amazonaws.com:5432/d35mju09ia8t41
services:
  - postgresql
before_script:
  - psql -c 'create database befit_test;' -U postgres
  - psql -c "CREATE USER username WITH PASSWORD 'password';" -U postgres

script: npm test


